### ISSUE TITLE
Promoting APAC Merchant Acceptance Solutions to QA environment

### ISSUE THREAD

**Issue by Eileenqfsv** [Fiserv/tenant-onboarding#17]
[PromotingToHigherEnv_18Jan23.pdf](https://github.com/Fiserv/tenant-onboarding/files/10442985/PromotingToHigherEnv_18Jan23.pdf)
@TaniaSarkar89 , as requested, APAC merchant acceptance solutions would like to seek support in promoting our documentation to the higher environment. Thank you for your support.

**Comment by TaniaSarkar89** [comment]
Closing this request as this request wasn't raised in the correct repository.
